### ISSUE TITLE
only works on macos

### ISSUE THREAD

**Issue by torpak** [deepakjois/gomp3#1]
It would be nice if the default branch wouldn't depend on platform specific libraries:
goinstall github.com/deepakjois/gomp3/src/mp3
/bin/bash: === cd /home/arne/go/src/pkg/github.com/deepakjois/gomp3/src/mp3; bash gomake -f- install
CGOPKGPATH=github.com/deepakjois/gomp3/src cgo --  mp3.go 
touch _obj/_cgo_run
6g  -o _go_.6  _obj/mp3.cgo1.go _obj/_cgo_gotypes.go
6c -FVw -I/home/arne/go/pkg/linux_amd64 -I . -o "_cgo_defun.6" _obj/_cgo_defun.c
gcc -m64 -I . -g -fPIC -O2 -o _cgo_main.o -c   _obj/_cgo_main.c
gcc -m64 -I . -g -fPIC -O2 -o mp3.cgo2.o -c   _obj/mp3.cgo2.c
gcc -m64 -I . -g -fPIC -O2 -o _cgo_export.o -c   _obj/_cgo_export.c
gcc -m64 -g -fPIC -O2 -o _cgo1_.o _cgo_main.o mp3.cgo2.o _cgo_export.o  -lmpg123 -lao -ldl -lm -framework CoreFoundation
gcc: CoreFoundation: No such file or directory
make: **\* [_cgo1_.o] Error 1

**Comment by deepakjois** [comment]
I know. As I said in the README, this is temporary. The fix will involve using an actual Makefile and using the GOOS environment variable to pull in the CoreFoundation framework only on OS X. Patches are welcome :)

As a workaround, you can just remove the `-framework CoreFoundation` in mp3.go and you will be good to go.

**Comment by torpak** [comment]
Project seems dead.
